In [360]:
import pandas as pd
import numpy as np
import os

## Đường dẫn tương đối theo cấu trúc project

In [361]:
current_dir = os.getcwd()
if os.path.exists(os.path.join('data', 'raw')):
    BASE_DIR = '.'
elif os.path.exists(os.path.join('..', 'data', 'raw')):
    BASE_DIR = '..'
else:
    raise FileNotFoundError("❌ Không tìm thấy thư mục data/raw.")

## Khởi tạo thư mục đích

In [362]:
RAW_DIR = os.path.join(BASE_DIR, "data", "raw")
CLEAN_DIR = os.path.join(BASE_DIR, "data", "processed", "clean")

os.makedirs(CLEAN_DIR, exist_ok=True)
print(f"✅ Đã thiết lập xong đường dẫn. Dữ liệu sạch sẽ được lưu tại: {CLEAN_DIR}")

✅ Đã thiết lập xong đường dẫn. Dữ liệu sạch sẽ được lưu tại: ..\data\processed\clean

## 1/File customers

# 1. Load data

In [363]:
df_cust = pd.read_csv(os.path.join(RAW_DIR, "customers.csv"))
df_cust.head()

,customer_id,zip,city,signup_date,gender,age_group,acquisition_channel
0,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media
1,2,15201,Hai Phong,2013-12-27,Female,45-54,email_campaign
2,3,15201,Hai Phong,2018-07-24,Female,18-24,organic_search
3,4,15201,Hai Phong,2017-11-29,Male,35-44,referral
4,5,15201,Hai Phong,2022-09-23,Male,55+,organic_search

## 1.1. Kiểm tra null và điền unknown vào ô trống

In [364]:
df_cust['acquisition_channel'] = df_cust['acquisition_channel'].fillna('unknown')
df_cust.head()

,customer_id,zip,city,signup_date,gender,age_group,acquisition_channel
0,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media
1,2,15201,Hai Phong,2013-12-27,Female,45-54,email_campaign
2,3,15201,Hai Phong,2018-07-24,Female,18-24,organic_search
3,4,15201,Hai Phong,2017-11-29,Male,35-44,referral
4,5,15201,Hai Phong,2022-09-23,Male,55+,organic_search

## 2. Ép kiểu và trích xuất thời gian

In [365]:

df_cust['signup_date'] = pd.to_datetime(df_cust['signup_date'])
df_cust['signup_year'] = df_cust['signup_date'].dt.year
df_cust['signup_month'] = df_cust['signup_date'].dt.month
df_cust.head()

,customer_id,zip,city,signup_date,gender,age_group,acquisition_channel,signup_year,signup_month
0,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media,2021,12
1,2,15201,Hai Phong,2013-12-27,Female,45-54,email_campaign,2013,12
2,3,15201,Hai Phong,2018-07-24,Female,18-24,organic_search,2018,7
3,4,15201,Hai Phong,2017-11-29,Male,35-44,referral,2017,11
4,5,15201,Hai Phong,2022-09-23,Male,55+,organic_search,2022,9

## 3. Lưu file

In [366]:
df_cust.to_csv(os.path.join(CLEAN_DIR, "customers_cleaned.csv"), index=False)
print(f"✅ Đã lưu customers_cleaned.csv với {len(df_cust)} dòng.")

✅ Đã lưu customers_cleaned.csv với 121930 dòng.

1.Xử lý dữ liệu Khách hàng (customers_cleaned.csv)
- Làm sạch (Cleaning): Xử lý các giá trị khuyết (Missing Values) tại cột acquisition_channel (kênh thu hút) bằng cách điền nhãn 'unknown' thay vì xóa dòng. Việc này giúp bảo toàn nguyên vẹn số lượng khách hàng.

- Tạo đặc trưng (Feature Engineering): Trích xuất signup_year (Năm đăng ký) và signup_month (Tháng đăng ký) từ cột signup_date ban đầu.

- Ý nghĩa Nghiệp vụ: Cung cấp sẵn các chiều dữ liệu thời gian để team Business dễ dàng xây dựng bộ lọc (Slicers) và phân tích xu hướng tăng trưởng tập khách hàng mới trên các Dashboard.

## 2/File geography

## 1. Load data

In [367]:
df_geo = pd.read_csv(os.path.join(RAW_DIR, "geography.csv"))
df_geo.head()

     zip       city region      district
0  15201  Hai Phong   East  District #13
1  15202     Phu Ly   East  District #13
2  15203   Viet Tri   East  District #13
3  15204  Bac Giang   East  District #13
4  15205  Bac Giang   East  District #13

## 2. Xóa trùng lặp mã zip

In [368]:
df_geo = df_geo.drop_duplicates(subset=['zip']).copy()
df_geo.head()

     zip       city region      district
0  15201  Hai Phong   East  District #13
1  15202     Phu Ly   East  District #13
2  15203   Viet Tri   East  District #13
3  15204  Bac Giang   East  District #13
4  15205  Bac Giang   East  District #13

## 3. Lưu file

In [369]:
df_geo.to_csv(os.path.join(CLEAN_DIR, "geography_cleaned.csv"), index=False)
print(f"✅ Đã lưu geography_cleaned.csv với {len(df_geo)} khu vực duy nhất.")

✅ Đã lưu geography_cleaned.csv với 39948 khu vực duy nhất.

2.Xử lý dữ liệu Địa lý (geography_cleaned.csv)
- Làm sạch (Cleaning): Chủ động kiểm tra và loại bỏ các dòng trùng lặp (Drop Duplicates) dựa trên khóa chính là mã bưu điện (zip).

- Ý nghĩa Nghiệp vụ: Đảm bảo tính duy nhất (Unique) của dữ liệu không gian. Đây là bước phòng thủ cực kỳ quan trọng để ngăn chặn lỗi "nổ dòng" (Data Explosion) làm sai lệch doanh thu khi thực hiện phép nối bảng (Left Join) với hệ thống bán hàng ở các bước sau.

## 3/File products

## 1. Load data

In [370]:
df_prod = pd.read_csv(os.path.join(RAW_DIR, "products.csv"))
df_prod.head()

,product_id,product_name,category,segment,size,color,price,cogs
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406

## 1.1. Xóa những sản phẩm bị thiếu thông tin về giá và sau đó in ra xem còn lại bao nhiêu sản phẩm đạt chuẩn.

In [371]:
df_prod = df_prod.dropna(subset=['price', 'cogs']).copy()
print(f"Sản phẩm hợp lệ: {len(df_prod)}")
df_prod.head()

Sản phẩm hợp lệ: 2412

,product_id,product_name,category,segment,size,color,price,cogs
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406

## 2. Tính Profit Margin

In [372]:
df_prod['profit_margin'] = (df_prod['price'] - df_prod['cogs']) / df_prod['price']
df_prod.head()

,product_id,product_name,category,segment,size,color,price,cogs,profit_margin
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875,0.1225
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254,0.4336
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278,0.2871
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954,0.4558
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406,0.1080

## 3. Lưu file

In [373]:
df_prod.to_csv(os.path.join(CLEAN_DIR, "products_cleaned.csv"), index=False)
print("✅ Đã lưu products_cleaned.csv")

✅ Đã lưu products_cleaned.csv

3.Xử lý dữ liệu Sản phẩm (products_cleaned.csv)
- Làm sạch (Cleaning): Loại bỏ hoàn toàn các sản phẩm bị khuyết thông tin price (Giá bán) hoặc cogs (Giá vốn).

- Tạo đặc trưng (Feature Engineering): Xây dựng chỉ số profit_margin (Biên lợi nhuận) cho từng mặt hàng theo công thức: (Giá bán - Giá vốn) / Giá bán.

- Ý nghĩa Nghiệp vụ: Các sản phẩm mất dấu vết tài chính không có giá trị phân tích kinh tế nên bắt buộc phải bị loại trừ. Đặc trưng Biên lợi nhuận mới tạo là thước đo cốt lõi giúp phân loại sản phẩm thành nhóm "gà đẻ trứng vàng" hay nhóm "sản phẩm mồi".

## 4/ File promotions

## 1. Load data

In [374]:
df_promo = pd.read_csv(os.path.join(RAW_DIR, "promotions.csv"))
df_promo.head()

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value
0,PROMO-0001,Spring Sale 2013,percentage,12.0,2013-03-18,2013-04-17,NaN,email,1,0
1,PROMO-0002,Mid-Year Sale 2013,percentage,18.0,2013-06-23,2013-07-22,NaN,online,0,0
2,PROMO-0003,Fall Launch 2013,percentage,10.0,2013-08-30,2013-10-02,NaN,email,0,0
3,PROMO-0004,Year-End Sale 2013,percentage,20.0,2013-11-18,2014-01-02,NaN,all_channels,0,50000
4,PROMO-0005,Urban Blowout 2013,fixed,50.0,2013-07-30,2013-09-02,Streetwear,online,0,150000

## 1.1. Fill NaN bằng 'All'

In [375]:
df_promo['applicable_category'] = df_promo['applicable_category'].fillna('All')
df_promo.isnull().sum()

promo_id               0
promo_name             0
promo_type             0
discount_value         0
start_date             0
end_date               0
applicable_category    0
promo_channel          0
stackable_flag         0
min_order_value        0
dtype: int64

In [376]:
df_promo.head()

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value
0,PROMO-0001,Spring Sale 2013,percentage,12.0,2013-03-18,2013-04-17,All,email,1,0
1,PROMO-0002,Mid-Year Sale 2013,percentage,18.0,2013-06-23,2013-07-22,All,online,0,0
2,PROMO-0003,Fall Launch 2013,percentage,10.0,2013-08-30,2013-10-02,All,email,0,0
3,PROMO-0004,Year-End Sale 2013,percentage,20.0,2013-11-18,2014-01-02,All,all_channels,0,50000
4,PROMO-0005,Urban Blowout 2013,fixed,50.0,2013-07-30,2013-09-02,Streetwear,online,0,150000

## 2. Tính số ngày diễn ra khuyến mãi

In [377]:
df_promo['start_date'] = pd.to_datetime(df_promo['start_date'])
df_promo['end_date'] = pd.to_datetime(df_promo['end_date'])
df_promo['promo_duration_days'] = (df_promo['end_date'] - df_promo['start_date']).dt.days
df_promo.head()

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value,promo_duration_days
0,PROMO-0001,Spring Sale 2013,percentage,12.0,2013-03-18,2013-04-17,All,email,1,0,30
1,PROMO-0002,Mid-Year Sale 2013,percentage,18.0,2013-06-23,2013-07-22,All,online,0,0,29
2,PROMO-0003,Fall Launch 2013,percentage,10.0,2013-08-30,2013-10-02,All,email,0,0,33
3,PROMO-0004,Year-End Sale 2013,percentage,20.0,2013-11-18,2014-01-02,All,all_channels,0,50000,45
4,PROMO-0005,Urban Blowout 2013,fixed,50.0,2013-07-30,2013-09-02,Streetwear,online,0,150000,34

## 3. Lưu file

In [378]:
df_promo.to_csv(os.path.join(CLEAN_DIR, "promotions_cleaned.csv"), index=False)
print("✅ Đã lưu promotions_cleaned.csv")

✅ Đã lưu promotions_cleaned.csv

4.Xử lý dữ liệu Khuyến mãi (promotions_cleaned.csv)
- Làm sạch (Cleaning): Gán nhãn 'All' cho các giá trị NaN tại cột applicable_category (Danh mục áp dụng).

- Tạo đặc trưng (Feature Engineering): Tính toán độ dài của chiến dịch promo_duration_days (Số ngày KM) bằng khoảng cách giữa ngày kết thúc và ngày bắt đầu.

- Ý nghĩa Nghiệp vụ: Việc gán 'All' phản ánh đúng thực tế: mã giảm giá không quy định danh mục nghĩa là áp dụng cho toàn sàn. Biến số thời lượng khuyến mãi là công cụ đắc lực để phân tích hiệu ứng FOMO (Sale chớp nhoáng) so với các chương trình duy trì dài hạn.

## 5/ File inventory

## 1. Load data

In [379]:
df_inv = pd.read_csv(os.path.join(RAW_DIR, "inventory.csv"))
df_inv.head()

,snapshot_date,product_id,stock_on_hand,units_received,units_sold,stockout_days,days_of_supply,fill_rate,stockout_flag,overstock_flag,reorder_flag,sell_through_rate,product_name,category,segment,year,month
0,2022-10-31,1,3,1,1,2,90.0,0.9333,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,10
1,2022-11-30,1,3,1,1,1,90.0,0.9667,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,11
2,2022-12-31,1,3,1,1,1,90.0,0.9667,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,12
3,2016-04-30,3,35,13,11,2,95.5,0.9333,1,1,0,0.2391,DragonWear MA-03,Casual,All-weather,2016,4
4,2016-05-31,3,36,11,10,1,108.0,0.9667,1,1,0,0.2174,DragonWear MA-03,Casual,All-weather,2016,5

## 1.1. Chuyển đổi dữ liệu của cột snapshot_date từ dạng chữ (text/string) sang dạng thời gian chuẩn (datetime)

In [380]:
df_inv['snapshot_date'] = pd.to_datetime(df_inv['snapshot_date'])
df_inv.head()

,snapshot_date,product_id,stock_on_hand,units_received,units_sold,stockout_days,days_of_supply,fill_rate,stockout_flag,overstock_flag,reorder_flag,sell_through_rate,product_name,category,segment,year,month
0,2022-10-31,1,3,1,1,2,90.0,0.9333,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,10
1,2022-11-30,1,3,1,1,1,90.0,0.9667,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,11
2,2022-12-31,1,3,1,1,1,90.0,0.9667,1,0,0,0.2500,DragonWear MA-01,Casual,All-weather,2022,12
3,2016-04-30,3,35,13,11,2,95.5,0.9333,1,1,0,0.2391,DragonWear MA-03,Casual,All-weather,2016,4
4,2016-05-31,3,36,11,10,1,108.0,0.9667,1,1,0,0.2174,DragonWear MA-03,Casual,All-weather,2016,5

## 2. Tính vòng quay hàng tồn (Cộng 1e-5 để tránh lỗi ZeroDivisionError)

In [381]:
df_inv['inventory_turnover'] = df_inv['units_sold'] / (df_inv['stock_on_hand'] + 1e-5)
df_inv[['product_id', 'stock_on_hand', 'units_sold', 'inventory_turnover']].head()

   product_id  stock_on_hand  units_sold  inventory_turnover
0           1              3           1            0.333332
1           1              3           1            0.333332
2           1              3           1            0.333332
3           3             35          11            0.314286
4           3             36          10            0.277778

## 3. Lưu file

In [382]:
df_inv.to_csv(os.path.join(CLEAN_DIR, "inventory_cleaned.csv"), index=False)
print("✅ Đã lưu inventory_cleaned.csv")

✅ Đã lưu inventory_cleaned.csv

5.Xử lý dữ liệu Tồn kho (inventory_cleaned.csv)
- Làm sạch (Cleaning): Chuẩn hóa kiểu dữ liệu (Type Casting) cho cột snapshot_date về đúng định dạng Datetime.

- Tạo đặc trưng (Feature Engineering): Tính toán inventory_turnover (Vòng quay tồn kho) bằng cách lấy số lượng bán chia cho lượng tồn kho hiện tại (cộng thêm một hằng số cực nhỏ 1e-5 để chống lỗi chia cho 0).

- Ý nghĩa Nghiệp vụ: Cung cấp góc nhìn thực tế về tốc độ giải phóng hàng hóa. Chỉ số này giúp quản lý chuỗi cung ứng nhận diện ngay lập tức các mặt hàng đang bị ứ đọng vốn (Turnover cực thấp) hoặc đang có nguy cơ cháy kho (Turnover cực cao).

## 6/ File web_trafic

## 1. Load data

In [383]:
df_web = pd.read_csv(os.path.join(RAW_DIR, "web_traffic.csv"))
df_web.head()

,date,sessions,unique_visitors,page_views,bounce_rate,avg_session_duration_sec,traffic_source
0,2013-01-01,9760,7253,39093,0.00514,102.9,organic_search
1,2013-01-02,10456,8151,47611,0.00406,120.5,organic_search
2,2013-01-03,10076,7458,36963,0.00401,263.6,direct
3,2013-01-04,9973,8063,53078,0.00562,151.8,direct
4,2013-01-05,10223,7882,36790,0.00525,168.6,referral

## 1.1. Chuyển đổi cột 'date' từ dạng chữ (text) sang dạng thời gian chuẩn (datetime)

In [384]:
df_web['date'] = pd.to_datetime(df_web['date'])
df_web.head()

,date,sessions,unique_visitors,page_views,bounce_rate,avg_session_duration_sec,traffic_source
0,2013-01-01,9760,7253,39093,0.00514,102.9,organic_search
1,2013-01-02,10456,8151,47611,0.00406,120.5,organic_search
2,2013-01-03,10076,7458,36963,0.00401,263.6,direct
3,2013-01-04,9973,8063,53078,0.00562,151.8,direct
4,2013-01-05,10223,7882,36790,0.00525,168.6,referral

## 2. Phân rã dữ liệu chuỗi thời gian thành day_of_week và is_weekend (ngày nghỉ)

In [385]:
df_web['day_of_week'] = df_web['date'].dt.day_name()
df_web['is_weekend'] = df_web['date'].dt.dayofweek.isin([5, 6]).astype(int)
df_web[['date', 'day_of_week', 'is_weekend']].head()

        date day_of_week  is_weekend
0 2013-01-01     Tuesday           0
1 2013-01-02   Wednesday           0
2 2013-01-03    Thursday           0
3 2013-01-04      Friday           0
4 2013-01-05    Saturday           1

## 3. Lưu file

In [386]:
df_web.to_csv(os.path.join(CLEAN_DIR, "web_traffic_cleaned.csv"), index=False)
print("✅ Đã lưu web_traffic_cleaned.csv")

✅ Đã lưu web_traffic_cleaned.csv

6.Xử lý dữ liệu Lưu lượng Web (web_traffic_cleaned.csv)
- Làm sạch (Cleaning): Đưa toàn bộ cột thời gian truy cập date về chuẩn định dạng ngày tháng.

- Tạo đặc trưng (Feature Engineering): Bóc tách day_of_week (Thứ trong tuần) và thiết lập cờ nhị phân is_weekend (1 = Cuối tuần, 0 = Ngày thường).

- Ý nghĩa Nghiệp vụ: Trang bị sẵn các bộ đếm thời gian linh hoạt. Phân hệ Marketing có thể đối chiếu trực tiếp hành vi lướt web và tỷ lệ chuyển đổi (Conversion Rate) giữa ngày thường và ngày nghỉ để tối ưu hóa ngân sách chạy quảng cáo.